export const GET_IMAGE_START = "GET_IMAGE_START";
export const GET_IMAGE_SUCCESS = "GET_IMAGE_SUCCESS";
export const GET_IMAGE_FAILED = "GET_IMAGE_FAILED";

export const TOGGLE_FAVORITE_IMAGE = "TOGGLE_FAVORITE_IMAGE";

export const SIGN_UP_START = "SIGN_UP_START";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";
