export const GET_IMAGE_START = "GET_IMAGE_START";
export const GET_IMAGE_SUCCESS = "GET_IMAGE_SUCCESS";
export const GET_IMAGE_FAILED = "GET_IMAGE_FAILED";

export const TOGGLE_FAVORITE_IMAGE = "TOGGLE_FAVORITE_IMAGE";
